#!/bin/bash
#
# eznixOS109bits -- Revision: 109r1 -- by eznix (https://sourceforge.net/projects/eznixos/)
# (GNU/General Public License version 3.0)
#
#--------------------------------
# Set variables
#--------------------------------
# Set date format
UDATE=$(date +%Y%m%d)
#
# Set working directory
WKDIR="$(pwd)"
#
#--------------------------------
# define functions
#--------------------------------
# Make project directory structure
ezblddir () {
mkdir -p $WKDIR/eznixOS109bits_$UDATE-1_all
mkdir -p $WKDIR/eznixOS109bits_$UDATE-1_all/usr/local/bin
mkdir -p $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109
mkdir -p $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/doc/eznixOS109
mkdir -p $WKDIR/eznixOS109bits_$UDATE-1_all/DEBIAN
}
#
# Copy files into project directories
ezcpfiles () {
cp -r $WKDIR/eznix109/bootloaders $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/hooks $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/icons $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/launchers $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/livebuild $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/scripts $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/sources $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/eznixOS109bits $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/doc $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp -r $WKDIR/eznix109/splash $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp $WKDIR/eznix109/doc/* $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/doc/eznixOS109/
cp $WKDIR/eznix109/eznixOS109bits/postinst $WKDIR/eznixOS109bits_$UDATE-1_all/DEBIAN/
cp $WKDIR/eznix109/bldeznix109 $WKDIR/eznixOS109bits_$UDATE-1_all/usr/share/eznixOS109/eznix109/
cp $WKDIR/eznix109/scripts/* $WKDIR/eznixOS109bits_$UDATE-1_all/usr/local/bin/
}
#
# Create control file
crtcontronl () {
cat <<EOT >> $WKDIR/eznixOS109bits_$UDATE-1_all/DEBIAN/control
Package: eznixOS109bits
Version: $UDATE-1
Section: base
Essential: no
Priority: optional
Architecture: all
Depends: live-build, curl, wget, apt-transport-https, dirmngr
Maintainer: eznix <https://sourceforge.net/projects/eznixos/>
Description: eznixOS109bits
 Updated eznixOS109 documentation and scripts
EOT
}
#
#----------------------------
# main program
#----------------------------
#
ezblddir
ezcpfiles
crtcontronl
# Build deb file
dpkg-deb --build eznixOS109bits_$UDATE-1_all && md5sum eznixOS109bits_$UDATE-1_all.deb > eznixOS109bits_$UDATE-1_all.md5
#
# Disclaimer:
#
# THIS SOFTWARE IS PROVIDED BY EZNIX “AS IS” AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL EZNIX BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#